author_id = "deadprogram"
app_id = "ghost-castle"
author_name = "Ron"
app_name = "Ghost Castle"

[files]
floor = { path = "floor.png" }
wall = { path = "wall.png" }
player = { path = "player.png" }
ghost = { path = "ghost.png" }
titlefont = { path = "font.fff", url = "https://fonts.fireflyzero.com/fonts/ascii/eg_6x10.fff" }
msgfont = { path = "msgfont.fff", url = "https://fonts.fireflyzero.com/fonts/ascii/eg_4x6.fff" }
